# Generated by Django 3.2.17 on 2023-03-19 09:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230319_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to='users/',
                verbose_name='аватарка пользователя',
            ),
        ),
    ]
