# Generated by Django 3.2.17 on 2023-03-19 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
    ]
