# Generated by Django 3.2.17 on 2023-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230322_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='freezing_account_data',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='день заморозки аккаунта'),
        ),
    ]
