# Generated by Django 3.2.17 on 2023-03-27 19:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            'users',
            '0006_rename_freezing_account_data_profile_freezing_account_date',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='users/',
                verbose_name='аватарка пользователя',
            ),
        ),
    ]
