# Generated by Django 3.2.17 on 2023-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_freezing_account_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='normalized_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Нормализованная почта'),
        ),
    ]
