# Generated by Django 3.2.17 on 2023-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_normalized_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='normalized_email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='Нормализованная почта'),
        ),
    ]
