# Generated by Django 3.2.17 on 2023-03-15 13:08

from django.db import migrations
from django.db import models
import django.db.models.deletion

import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата написания'
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        default='user_mail@example.com',
                        help_text='Введите почту',
                        max_length=254,
                        verbose_name='почта',
                    ),
                ),
                (
                    'status',
                    models.TextField(
                        choices=[
                            ('получено', 'получено'),
                            ('в обработке', 'в обработке'),
                            ('ответ дан', 'ответ дан'),
                        ],
                        default='получено',
                        verbose_name='статус',
                    ),
                ),
            ],
            options={
                'verbose_name': 'фидбэк',
                'verbose_name_plural': 'фидбэки',
            },
        ),
        migrations.CreateModel(
            name='FeedbackText',
            fields=[
                (
                    'feedback',
                    models.OneToOneField(
                        help_text='Напишите ваш отзыв',
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='feedback.feedback',
                        verbose_name='Текст',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        blank=True,
                        help_text='Напишите отзыв о нашем сайте',
                        null=True,
                        verbose_name='фидбэк',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Текст фидбека',
                'verbose_name_plural': 'Тексты фидбека',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'files',
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to=feedback.models.FeedbackFiles.saving_path,
                        verbose_name='файлы',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        default=None,
                        help_text='Прикрепите файлы',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='feedback.feedback',
                        verbose_name='Файлы',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Файл фидбека',
                'verbose_name_plural': 'Файлы фидбека',
            },
        ),
    ]
