# Generated by Django 3.2.17 on 2023-03-12 17:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Напишите отзыв о нашем сайте',
                        verbose_name='фидбэк',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата написания'
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        default='user_mail@example.com',
                        help_text='Введите почту',
                        max_length=254,
                        verbose_name='почта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'фидбэк',
                'verbose_name_plural': 'фидбэки',
            },
        ),
    ]
