# Generated by Django 3.2.17 on 2023-03-12 18:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.TextField(
                choices=[
                    ('получено', 'получено'),
                    ('в обработке', 'в обработке'),
                    ('ответ дан', 'ответ дан'),
                ],
                default='получено',
                verbose_name='статус',
            ),
        ),
    ]
