# Generated by Django 3.2.17 on 2023-03-15 18:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0002_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('получено', 'Получено'),
                    ('в обработке', 'в обработке'),
                    ('ответ дан', 'ответ дан'),
                ],
                default='получено',
                max_length=11,
            ),
        ),
    ]
