# Generated by Django 3.2.17 on 2023-03-27 18:44

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ('rating', '0001_initial'),
        ('rating', '0002_mark_mark'),
        ('rating', '0003_auto_20230326_2320'),
    ]

    initial = True

    dependencies = [
        (
            'users',
            '0006_rename_freezing_account_data_profile_freezing_account_date',
        ),
        (
            'catalog',
            '0002_auto_20230223_2243_squashed_0011_auto_20230310_1408',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users.person',
                        verbose_name='кто поставил оценку?',
                    ),
                ),
                (
                    'mark',
                    models.IntegerField(
                        choices=[
                            (1, 'Ненависть'),
                            (2, 'Неприязнь'),
                            (3, 'Нейтрально'),
                            (4, 'Обожание'),
                            (5, 'Любовь'),
                        ],
                        default=0,
                        help_text='оцените товар',
                        verbose_name='оценка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
            },
        ),
    ]
