# Generated by Django 3.2.17 on 2023-03-28 16:07

from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_profile_image'),
        (
            'catalog',
            '0002_auto_20230223_2243_squashed_0011_auto_20230310_1408',
        ),
        ('rating', '0001_squashed_0003_auto_20230326_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date_created',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='когда была поставлена оценка?',
                verbose_name='время создания',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='item',
            field=models.ForeignKey(
                help_text='товар, на который поставлена оценка',
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.item',
                verbose_name='товар',
            ),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(
                choices=[
                    (1, 'ненависть'),
                    (2, 'неприязнь'),
                    (3, 'нейтрально'),
                    (4, 'обожание'),
                    (5, 'любовь'),
                ],
                help_text='оцените товар',
                verbose_name='оценка',
            ),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(
                help_text='кто поставил оценку?',
                on_delete=django.db.models.deletion.CASCADE,
                to='users.person',
                verbose_name='пользователь',
            ),
        ),
    ]
