# Generated by Django 3.2.17 on 2023-02-23 22:43

from django.db import migrations
from django.db import models
import django.db.models.deletion

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_squashed_0002_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                default=None,
                help_text='Опишите товар',
                validators=[catalog.models.ValidateMustContain],
                verbose_name='Описание',
            ),
        ),
    ]
