# Generated by Django 3.2.17 on 2023-03-24 11:56

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0002_auto_20230223_2243'), ('catalog', '0003_auto_20230226_1035'), ('catalog', '0004_remove_item_image'), ('catalog', '0005_item_is_on_main'), ('catalog', '0006_auto_20230309_1100'), ('catalog', '0007_auto_20230309_1101'), ('catalog', '0008_auto_20230309_1149'), ('catalog', '0009_auto_20230310_1300'), ('catalog', '0010_auto_20230310_1408'), ('catalog', '0011_auto_20230310_1408')]

    dependencies = [
        ('catalog', '0001_squashed_0002_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None, help_text='Опишите товар', validators=[catalog.models.ValidateMustContain], verbose_name='Описание'),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items', 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='catalog.Tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None, help_text='Опишите товар', validators=[catalog.models.ValidateMustContain('превосходно', 'роскошно')], verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='catalog/', verbose_name='изображение товара')),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='catalog/', verbose_name='изображение товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотогалерея товара',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AddField(
            model_name='item',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
