# Generated by Django 3.2.17 on 2023-02-21 21:30

from django.db import migrations
from django.db import models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_name',
            field=models.CharField(
                default=None, editable=False, max_length=150, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                default=None,
                help_text='Опишите товар',
                validators=[catalog.models.validate_must_contain],
                verbose_name='Описание',
            ),
        ),
    ]
