# Generated by Django 3.2.17 on 2023-02-19 20:01

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230219_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите назовите', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Введите назовите', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None, help_text='Опишите товар', validators=[catalog.models.excellent_or_luxurious_in_field_validator], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите назовите', max_length=150, verbose_name='Название'),
        ),
    ]
