# Generated by Django 3.2.17 on 2023-02-26 10:35

from django.db import migrations
from django.db import models
import django.db.models.deletion

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_20230223_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={
                'default_related_name': 'items',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to='catalog/',
                verbose_name='изображение товара',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='catalog.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='items', to='catalog.Tag'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                default=None,
                help_text='Опишите товар',
                validators=[
                    catalog.models.ValidateMustContain(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='Описание',
            ),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to='catalog/',
                        verbose_name='изображение товара',
                    ),
                ),
                (
                    'item',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to='catalog/',
                        verbose_name='изображение товара',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотогалерея товара',
            },
        ),
    ]
