# Generated by Django 3.2.17 on 2023-02-21 06:18

from django.db import migrations
from django.db import models
import django.db.models.deletion

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Напишите URL slug вашей категории',
                max_length=200,
                unique=True,
                verbose_name='URL slug',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                default=None,
                help_text='Опишите товар',
                validators=[catalog.models.validate_must_contain],
                verbose_name='Описание',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Напишите URL slug вашего товара',
                max_length=200,
                unique=True,
                verbose_name='URL slug',
            ),
        ),
    ]
