# Generated by Django 3.2.17 on 2023-02-27 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_auto_20230226_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
