# Generated by Django 3.2.17 on 2023-02-21 22:00

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None, help_text='Опишите товар', validators=[catalog.models.validate_must_contain], verbose_name='Описание'),
        ),
    ]
