# Generated by Django 3.2.17 on 2023-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_auto_20230309_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='change_time',
            field=models.DateField(
                auto_now=True, verbose_name='Дата изменения'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_time',
            field=models.DateField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
    ]
