# Generated by Django 3.2.17 on 2023-03-09 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0007_auto_20230309_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='change_time',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='creation_time',
            new_name='creation_date',
        ),
    ]
